[phases.setup]
nixPkgs = ["nodejs_20", "php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mysqli"]

[phases.install]
cmds = ["cd client && npm install"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t server"
